### ISSUE TITLE
Tutorial and Documentation for on-the-fly MDEF

### ISSUE THREAD

**Issue by reinimaurer1** [NQCD/NQCDynamics.jl#124]
We discussed that it would be nice to also showcase that the code in principle can perform on the fly dynamics on realistic systems. 
One way to do that is to take one of the H2 on Ag(111) trajectories that @oadoug has simulated with the code and run on the fly dynamics with NQCD and FHIaims via the ASE interface. 
This means the NQCD code drives the dynamics using an ASE calculator for FHIaims. 
That calculator has a get_forces() and get_friction() function.
It's enough to do this for one set of initial conditions to show that it is principally possible.

**Comment by jamesgardner1421** [comment]
This should be quite doable with just a small change. The AdiabaticASEModel currently implements on the potential and forces functions. So a copy of this should be made that also implements the friction function. This will have to handle the unit conversions as well.

The new type should be something like `FrictionASEModel <: AdiabaticFrictionModel` and should implement `potential`, `derivative!` and `friction!` similarly to the existing models.
