### ISSUE TITLE
LDFA: Gerrits model

### ISSUE THREAD

**Issue by smjanke** [NQCD/NQCDynamics.jl#127]
https://github.com/NQCD/NonadiabaticMolecularDynamics.jl/blob/685eb31fd86a54c6f21ef75f4e61bdd389960dd4/docs/src/nonadiabaticmodels/ldfa.md#L17

For which systems is the friction coefficient evaluated and under what circumstances is it evaluated (i.e., where does the electron density come from)? Are these numbers you just read in that are tabulated in the paper or is this a routine that you need to call first? If you need to call it first, please provide an example of how to do that.

**Comment by jamesgardner1421** [comment]
Similar to #128. We should talk more about the CubeLDFAModel and how this converts the cube file density into the friction coefficient. We also need to fix the giant pictures.
