### ISSUE TITLE
Initial Sampling

### ISSUE THREAD

**Issue by smjanke** [NQCD/NQCDynamics.jl#130]
https://github.com/NQCD/NonadiabaticMolecularDynamics.jl/blob/685eb31fd86a54c6f21ef75f4e61bdd389960dd4/docs/src/initialconditions/dynamicaldistribution.md#L49

Can you be more specific as to which docstring one would need to look at?

**Comment by jamesgardner1421** [comment]
You just have to click on the link in the previous sentence. I didn't make this very clear. This can be reworked to make it obvious that's what I mean.
