### ISSUE TITLE
Metropolis Hastings, Legacy version

### ISSUE THREAD

**Issue by smjanke** [NQCD/NQCDynamics.jl#136]
https://github.com/NQCD/NonadiabaticMolecularDynamics.jl/blob/f194f7380535af288303c15967ac2312bd6e85e9/docs/src/initialconditions/samplingmethods/metropolishastings.md#L29

Why are you describing the legacy version if you plan to eliminate it, anyway? Does it offer any advantages or other features than the current version? In case it doesn't do the latter and really has no reason why anyone would use it over the AdvanceHM.jl, I would not mention it in the documentation, since you're planing to delete it, anyway. You don't want anyone to start using it.

It is very nicely explained section in terms of parameters and output.

**Comment by reinimaurer1** [comment]
The docs should only mention the new version, but we don't have to delete the old one

**Comment by Alexsp32** [comment]
Maybe update docs

**Comment by Alexsp32** [comment]
#325 removes the legacy method from the docs since everything should be covered in some way by the interface to AdvancedMH.jl
