### ISSUE TITLE
Ensemble simulations

### ISSUE THREAD

**Issue by smjanke** [NQCD/NQCDynamics.jl#223]
https://github.com/NQCD/NQCDynamics.jl/blob/619997c6683d17e0df79a7aaddc6d2b397cad625/docs/src/ensemble_simulations.md?plain=1#L26

What does the (1,1) mean?

**Comment by jamesgardner1421** [comment]
This is the size of the sample taken from the distribution. So it matches (n_dofs, n_atoms). An extra sentence explainging this would be good.
