### ISSUE TITLE
Metropolis-Hastings Monte Carlo: Improve move_ratio kwarg

### ISSUE THREAD

**Issue by Alexsp32** [NQCD/NQCDynamics.jl#321]
I would suggest two (breaking) changes to `run_advancedmh_sampling` ([Code](https://github.com/NQCD/NQCDynamics.jl/blob/f7d45ab8089903831f8c41efc49e865d502679b8/src/InitialConditions/ThermalMonteCarlo.jl#L30)):

1. **Substitute `move_ratio` for its inverse:** To me, it seems more logical for a move ratio of 0 to prevent the entire system from moving, while 1 causes the entire system to move. Doing it the other way round seems weird to me. Possibly we could split from `move_ratio` into `stop_ratio` and `movement_ratio`, where `stop_ratio=1-movement_ratio` and deprecate `move_ratio` to avoid breaking stuff. 
2. **Ignore zero moves when deciding the fraction of the system to perturb:** In systems where certain atoms should remain in place, they are assigned Dirac distributions centred at their starting position. Currently, their "movement" is included in the movement ratio during sampling. I would propose ignoring zero moves when applying the movement ratio to avoid generating moves containing identical structures to the previous ones.

**Comment by Alexsp32** [comment]
I forgot to mention `internal_ratio` for the Ring polymer analogy, but same issue here.

**Comment by reinimaurer1** [comment]
In general, the keywords should be as descriptive as possible. `move_ratio` to me also suggests that 1 is a high "ratio". 
Please don't forget to describe the behaviour in the function and to update the docs/tutorial

**Comment by Alexsp32** [comment]
Docs are updated to include information about the changes: https://nqcd.github.io/NQCDynamics.jl/previews/PR325/initialconditions/metropolishastings/
