### ISSUE TITLE
Fix NRPMD for calculating scattering probabilities (Tully models)

### ISSUE THREAD

**Issue by wgst** [NQCD/NQCDynamics.jl#88]

**Comment by jamesgardner1421** [comment]
What is the problem at the moment? Is there a bug or are the results not good?

**Comment by wgst** [comment]
It's just that OutputStateResolvedScattering1D needed for scattering tests requires function get_adiabatic_population, which isn't included in nrpmd module.

**Comment by jamesgardner1421** [comment]
Ah ok, have a go at implementing it and see what happens. For the Tully models the adiabatic and diabatic populations are equivalent outside of the interaction region anyway so you can always use the diabatic populations instead if it's easier
